---
- name: Deploy Flask App with Docker and Docker Compose
  hosts: localhost
  become: yes
  vars:
    app_path: "{{ lookup('env', 'PWD') }}"

  tasks:
    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Show current directory (PWD)
      debug:
        msg: "Current working directory is: {{ lookup('env', 'PWD') }}"

    - name: Build and start Docker containers with Docker Compose
      docker_compose:
        project_src: "{{ app_path }}/ansible"
        build: yes
        restarted: yes
        stopped: no


