---
- name: Deploy Flask App with Docker and Docker Compose
  hosts: localhost
  become: yes
  vars:
    app_path: "{{ lookup('env', 'PWD') }}"

  tasks:
#    - name: Ensure Docker is installed
#      package:
#        name: docker.io
#        state: present

    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Create project directory
      file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'

    - name: Copy Flask application files
      copy:
        src: "{{ app_path }}"
        dest: "/home/user/app"  # Adjust destination path as necessary
        owner: root
        group: root
        mode: '0755'
      with_items:
        - app.py
        - Dockerfile
        - docker-compose.yml
        - requirements.txt

    - name: Build and start Docker containers with Docker Compose
      docker_compose:
        project_src: "{{ app_path }}"
        build: yes
        restarted: yes
        stopped: no


    - name: Ensure Docker container is running
      docker_container:
        name: web
        image: "shlomiaz/flask_app_image_name:latest"
        state: started
        restart_policy: always