version: '3.7'

services:
  web:
    build: .
    image: flask_app_image_name:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_PATH=/data/hits.json
    volumes:
      - app_data:/data

  db:
    image: alpine
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumes:
      - app_data:/data

volumes:
  app_data:
    driver: local
